/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Macéo
 */

public class NewJFrame extends javax.swing.JFrame {
    private Cadenas jeu;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
public NewJFrame() {
    initComponents();
    jeu = new Cadenas(10);        // par défaut : mode facile
    initialiserInterface();
}

private void initialiserInterface() {

    texte_intro.setText("Trouvez le bon code en moins de " + jeu.getMaxTentatives() + " tentatives!");
    texte_nb_tentatives.setText("0 sur " + jeu.getMaxTentatives());
    texte_chiffre_0.setText("0");
    texte_chiffre_1.setText("0");
    texte_chiffre_2.setText("0");
    texte_chiffre_3.setText("0");

    texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts :");
    texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop hauts :");
    texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");

    texte_nb_chiffres_exacts.setText("0");
    texte_nb_chiffres_haut.setText("0");
    texte_nb_chiffres_bas.setText("0");

    texte_tentatives.setText("Tentatives");
    texte_nb_tentatives.setText("0 sur " + jeu.getMaxTentatives());
}

private int incrementer(int valeur) {
    return (valeur + 1) % 10;
}

private int decrementer(int valeur) {
    return (valeur + 9) % 10;   // -1 modulo 10
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        texte_nb_tentatives = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        texte_intro = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        bouton_facile = new javax.swing.JButton();
        bouton_normal = new javax.swing.JButton();
        bouton_difficile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_chiffre_0.setText("0");
        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, 37, -1));

        texte_chiffre_1.setText("0");
        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 101, 37, -1));

        texte_chiffre_2.setText("0");
        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 101, 37, -1));

        texte_chiffre_3.setText("0");
        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 101, 37, -1));

        bouton_tester.setText("Tester");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 98, -1, -1));

        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts:");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 187, -1, -1));

        texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop hauts:");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 215, 196, -1));

        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas:");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 237, 198, -1));

        texte_tentatives.setText("Tentatives");
        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 180, 68, -1));

        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 293, -1, -1));

        texte_nb_tentatives.setText("0 sur 5");
        getContentPane().add(texte_nb_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 237, 68, -1));

        up_chiffre_1.setText("▲");
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, -1, -1));

        up_chiffre_2.setText("▲");
        up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 69, -1, -1));

        up_chiffre_3.setText("▲");
        up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 69, -1, -1));

        up_chiffre_4.setText("▲");
        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 69, -1, -1));

        down_chiffre_4.setText("▼");
        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 139, -1, -1));

        down_chiffre_3.setText("▼");
        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 139, -1, -1));

        down_chiffre_2.setText("▼");
        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 139, -1, -1));

        down_chiffre_1.setText("▼");
        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, -1, -1));

        texte_intro.setText("Trouvez le bon code en moins de 10 tentatives!");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 21, -1, -1));

        texte_nb_chiffres_exacts.setText("0");
        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 187, 37, -1));

        texte_nb_chiffres_haut.setText("0");
        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 215, 37, -1));

        texte_nb_chiffres_bas.setText("0");
        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 237, 37, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        bouton_facile.setText("Facile");
        bouton_facile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_facileActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_facile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        bouton_normal.setText("Normal");
        bouton_normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_normalActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        bouton_difficile.setText("Difficile");
        bouton_difficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_difficileActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_difficile, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
    int v = Integer.parseInt(texte_chiffre_0.getText());
    texte_chiffre_0.setText(String.valueOf(incrementer(v)));
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
    int v = Integer.parseInt(texte_chiffre_1.getText());
    texte_chiffre_1.setText(String.valueOf(incrementer(v)));
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
    int v = Integer.parseInt(texte_chiffre_2.getText());
    texte_chiffre_2.setText(String.valueOf(incrementer(v)));
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
    int v = Integer.parseInt(texte_chiffre_3.getText());
    texte_chiffre_3.setText(String.valueOf(incrementer(v)));
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
    int v = Integer.parseInt(texte_chiffre_0.getText());
    texte_chiffre_0.setText(String.valueOf(decrementer(v)));
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
    int v = Integer.parseInt(texte_chiffre_1.getText());
    texte_chiffre_1.setText(String.valueOf(decrementer(v)));
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
    int v = Integer.parseInt(texte_chiffre_2.getText());
    texte_chiffre_2.setText(String.valueOf(decrementer(v)));
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
    int v = Integer.parseInt(texte_chiffre_3.getText());
    texte_chiffre_3.setText(String.valueOf(decrementer(v)));
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
    int[] prop = new int[4];
    prop[0] = Integer.parseInt(texte_chiffre_0.getText());
    prop[1] = Integer.parseInt(texte_chiffre_1.getText());
    prop[2] = Integer.parseInt(texte_chiffre_2.getText());
    prop[3] = Integer.parseInt(texte_chiffre_3.getText());

    int[] res = jeu.testerProposition(prop);


    texte_nb_chiffres_exacts.setText(String.valueOf(res[0]));
    texte_nb_chiffres_haut.setText(String.valueOf(res[1]));
    texte_nb_chiffres_bas.setText(String.valueOf(res[2]));

    texte_nb_tentatives.setText(jeu.getNbTentatives() + " sur " + jeu.getMaxTentatives());

    if (jeu.estGagne(res)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Bravo, vous avez trouvé le code !");
        bouton_tester.setEnabled(false);
    } else if (jeu.estFini(res)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Perdu, nombre de tentatives atteint.");
        bouton_tester.setEnabled(false);
    }
    
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
    jeu = new Cadenas();      // nouveau code secret
    initialiserInterface();
    bouton_tester.setEnabled(true);

    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void bouton_facileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_facileActionPerformed
    jeu = new Cadenas(10);
    initialiserInterface();
    bouton_tester.setEnabled(true);
    }//GEN-LAST:event_bouton_facileActionPerformed

    private void bouton_normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_normalActionPerformed
    jeu = new Cadenas(5);
    initialiserInterface();
    bouton_tester.setEnabled(true);
    }//GEN-LAST:event_bouton_normalActionPerformed

    private void bouton_difficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_difficileActionPerformed
    jeu = new Cadenas(3);
    initialiserInterface();
    bouton_tester.setEnabled(true);
    }//GEN-LAST:event_bouton_difficileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_difficile;
    private javax.swing.JButton bouton_facile;
    private javax.swing.JButton bouton_normal;
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_tentatives;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
