/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Macéo
 */
import java.util.ArrayList;
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
    private ArrayList<Question> questions;
    private int indexQuestionCourante = 0;
    private int score = 0;
   
    public FenetreQuiz() {
        initComponents();
        questions = new ArrayList<>();
        questions.add(new Question("Q1", "Prop1A", "Prop1B", "Prop1C", "Prop1D", 2));
        questions.add(new Question("Q2", "Prop2A", "Prop2B", "Prop2C", "Prop2D", 3));
        questions.add(new Question("Q3", "Prop3A", "Prop3B", "Prop3C", "Prop3D", 1));
        questions.add(new Question("Q4", "Prop4A", "Prop4B", "Prop4C", "Prop4D", 2));
        questions.add(new Question("Q5", "Prop5A", "Prop5B", "Prop5C", "Prop5D", 4));
        Question q = questions.get(indexQuestionCourante);
        jLabel1.setText(q.getIntitule());
        jLabel2.setVisible(false);
        jLabelScore.setVisible(false);
        jLabelScore.setText("Score : " + score);
        jButtonSuivant.setText("Question Suivante");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jButtonSuivant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1b1Question");

        jButton1.setText("btnRep1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("btnRep2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("btnRep3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("btnRep4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabelScore.setText("jLabel3");

        jButtonSuivant.setText("jButton5");
        jButtonSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuivantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelScore)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSuivant)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonSuivant))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel2.setVisible(true);
        Question q = questions.get(indexQuestionCourante);
if (q.getIndexBonneReponse() == 1) {
    score++;
    jLabelScore.setVisible(true);
    jLabelScore.setText("Score : " + score);
    jLabel2.setText("Bonne réponse !");
} else {
    jLabel2.setText("Mauvaise réponse !");
}
jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel2.setVisible(true);
          
                 Question q = questions.get(indexQuestionCourante);
if (q.getIndexBonneReponse() == 2) {
    score++;
    jLabelScore.setVisible(true);
    jLabelScore.setText("Score : " + score);
    jLabel2.setText("Bonne réponse !");
} else {
    jLabel2.setText("Mauvaise réponse !");
}
         jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLabel2.setVisible(true);
      
                 Question q = questions.get(indexQuestionCourante);
if (q.getIndexBonneReponse() == 3) {
    score++;
    jLabelScore.setVisible(true);
    jLabelScore.setText("Score : " + score);
    jLabel2.setText("Bonne réponse !");
} else {
    jLabel2.setText("Mauvaise réponse !");
}
         jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jLabel2.setVisible(true);
       
                 Question q = questions.get(indexQuestionCourante);
if (q.getIndexBonneReponse() == 4) {
    score++;
    jLabelScore.setVisible(true);
    jLabelScore.setText("Score : " + score);
    jLabel2.setText("Bonne réponse !");
} else {
    jLabel2.setText("Mauvaise réponse !");
}
        jButton4.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuivantActionPerformed
indexQuestionCourante++;

if (indexQuestionCourante < questions.size()) {
    // Encore des questions, on affiche la suivante
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    jButton3.setEnabled(true);
    jButton4.setEnabled(true);

    Question q = questions.get(indexQuestionCourante);
    jLabel1.setText(q.getIntitule());
    jButton1.setText(q.getProposition1());
    jButton2.setText(q.getProposition2());
    jButton3.setText(q.getProposition3());
    jButton4.setText(q.getProposition4());

    // Met à jour le score si besoin
    jLabelScore.setText("Score : " + score);
} else {
    // Fin du quiz : on affiche le score final
    jLabel1.setText("Quiz terminé. Score : " + score + " / " + questions.size());

    // On désactive tous les boutons pour ne plus cliquer
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    jButtonSuivant.setEnabled(false); // si tu as ce bouton pour changer de question
}
    }//GEN-LAST:event_jButtonSuivantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonSuivant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelScore;
    // End of variables declaration//GEN-END:variables
}
